FROM python:3.11-slim-bookworm

WORKDIR /app

RUN apt-get update && apt-get install -y postgresql-client && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app ./app
COPY ./alembic.ini .
COPY ./alembic ./alembic

# Expose the port the app runs on
EXPOSE 8080

# Define the command to run the application
# We will override this with 'command:' in docker-compose to run the migration first
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]